@startuml Uses Hierarchy
hide empty description
left to right direction

state Audio360Software {
    ' Hardware Modules
    state Microcontroller #lightblue
    state "Microphone Input Module" as micInput #lightblue
    state "USART Communication Module" as usart #lightblue
    state "SD Card Interface Module" as sd #lightblue


    ' Software Modules
    state "Microphone Diagnostic Module" as MicDiag #lightgreen
    state "DOA Processor Module" as DOA #lightgreen
    state "Audio360 Engine Module" as Audio360Eng #lightgreen
    state "Audio Sampling Module" as AudioSampling #lightgreen
    state "Audio Spectral Leakage Prevention Module" as SpectralLeakage #lightgreen
    state "Audio Normalizer Module" as AudioNormalize #lightgreen
    state "Audio Anomaly Detection Module" as AudioAnomaly #lightgreen
    state "Logging Module" as Logging #lightgreen
    state "Fast Fourier Transform Module" as fft #lightgreen
    state "Fault Manager Module" as FaultManager #lightgreen
    state "Mel Filter Module" as Mel #lightgreen
    state "Discret Cosine Transform Module" as DisreteCos #lightgreen
    state "Principle Component Analysis Module" as PCA #lightgreen
    state "Linear Discriminant Analysis Module" as LDA #lightgreen
    state "Classification Module" as Classification #lightgreen
    state "Independent Component Analysis Module" as ICA #lightgreen
    state "Visualization Module" as Viz #lightgreen

    ' Mocks
    state "Audio Generation Module" as AudioGen #MOTIVATION

    DOA --> AudioGen
    MicDiag --> micInput
    fft --> Microcontroller
    fft --> SpectralLeakage

    DOA --> AudioSampling
    DOA --> ICA
    FaultManager --> Audio360Eng
    Audio360Eng --> DOA
    Audio360Eng --> Classification
    Audio360Eng --> Logging
    AudioSampling --> micInput
    AudioSampling --> MicDiag
    AudioAnomaly --> AudioSampling
    Logging --> usart
    Logging --> sd
    FaultManager --> DOA
    FaultManager --> AudioAnomaly
    FaultManager --> Classification
    Classification --> AudioNormalize
    Classification --> Mel
    Classification --> DisreteCos
    Classification --> PCA
    Classification --> LDA
    Classification --> fft
    Classification --> ICA
    Viz --> Audio360Eng

    micInput --> Microcontroller
    usart --> Microcontroller
    sd --> Microcontroller
}

@enduml
